#!/usr/bin/env node
// probe-ab.mjs — A/B behavioral probe harness for Ulysses workspace changes.
//
// Runs an identical scripted prompt against a "before" and "after" workspace pair
// and captures one concrete observable metric per probe. Results are written to a
// JSON file for human review. The pass criterion is a directional improvement
// (e.g., "after reduces grep calls by ≥2") rather than an absolute value, because
// model variance makes exact counts unreliable.
//
// Usage:
//   node scripts/probe-ab.mjs \
//     --workspace-before <path>   freshly scaffolded workspace WITHOUT the change
//     --workspace-after  <path>   freshly scaffolded workspace WITH the change
//     --fixture          <path>   fixture repo generated by probe-fixture.mjs
//     --probe            <name>   one of: lsp-callers | codebase-map | scoped-test | session-reflect
//     --output           <path>   JSON file to write results
//
// Supported probes:
//   lsp-callers     Find all callers of _toMs. Metric: grep calls before correct answer.
//                   Pass: after uses ≥2 fewer grep calls (or 0 false positives).
//                   Note: after workspace requires a running LSP server.
//   codebase-map    Find all callers of _toMs with CODEBASE.md present vs absent.
//                   Metric: filesystem exploration tool calls (Read/Grep/LS) before answer.
//                   Pass: after reduces exploration calls by ≥2.
//   scoped-test     Run scoped test command from a per-repo CLAUDE.md vs a monorepo-wide run.
//                   Metric: number of irrelevant test-file invocations.
//                   Pass: after eliminates monorepo-wide invocations.
//   session-reflect After a scripted session containing "actually", assert session-reflect.json
//                   exists with ≥1 candidate.
//                   Pass: file present with candidates.length ≥ 1.
//
// Exit codes:
//   0 — flags parsed, probe skeleton executed (or stub), result file written (or usage printed)
//   1 — unexpected error

import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { dirname, resolve } from 'path';
import { parseArgs } from 'util';

const PROBES = ['lsp-callers', 'codebase-map', 'scoped-test', 'session-reflect'];

function printUsage() {
  process.stdout.write(
    [
      'Usage: node scripts/probe-ab.mjs \\',
      '  --workspace-before <path>   workspace WITHOUT the change under test',
      '  --workspace-after  <path>   workspace WITH the change under test',
      '  --fixture          <path>   fixture repo (output of probe-fixture.mjs)',
      '  --probe            <name>   probe to run: ' + PROBES.join(' | '),
      '  --output           <path>   JSON file to write results',
      '',
      'Probes:',
      '  lsp-callers     Metric: grep calls before finding all _toMs callers',
      '                  Pass: after uses ≥2 fewer grep calls',
      '  codebase-map    Metric: filesystem exploration calls before correct answer',
      '                  Pass: after reduces exploration calls by ≥2',
      '  scoped-test     Metric: monorepo-wide test invocations in before vs after',
      '                  Pass: after eliminates monorepo-wide runs',
      '  session-reflect Metric: session-reflect.json candidates after scripted correction',
      '                  Pass: file present with candidates.length ≥ 1',
    ].join('\n') + '\n'
  );
}

// Parse flags
let values;
try {
  ({ values } = parseArgs({
    options: {
      'workspace-before': { type: 'string' },
      'workspace-after': { type: 'string' },
      fixture: { type: 'string' },
      probe: { type: 'string' },
      output: { type: 'string' },
    },
    strict: false,
  }));
} catch (err) {
  process.stderr.write(`Flag parse error: ${err.message}\n`);
  printUsage();
  process.exit(0);
}

const workspaceBefore = values['workspace-before'];
const workspaceAfter = values['workspace-after'];
const fixture = values.fixture;
const probe = values.probe;
const output = values.output;

// If required flags are missing, print usage and exit 0 per spec.
if (!workspaceBefore || !workspaceAfter || !fixture || !probe || !output) {
  printUsage();
  process.exit(0);
}

// Validate probe name.
if (!PROBES.includes(probe)) {
  process.stderr.write(`Unknown probe: ${probe}\nMust be one of: ${PROBES.join(', ')}\n`);
  printUsage();
  process.exit(0);
}

// Result skeleton — the verify phase fills in the runner implementations.
const result = {
  probe,
  workspaceBefore: resolve(workspaceBefore),
  workspaceAfter: resolve(workspaceAfter),
  fixture: resolve(fixture),
  runAt: new Date().toISOString(),
  before: {
    toolCallLog: [],   // TODO: implement — extract from transcript or hook logs
    metric: null,      // TODO: implement — the single number defined per probe
    correctAnswer: null,
  },
  after: {
    toolCallLog: [],   // TODO: implement
    metric: null,      // TODO: implement
    correctAnswer: null,
  },
  delta: null,         // TODO: implement — after.metric - before.metric (direction: negative = improvement)
  passed: null,        // TODO: implement — true if delta meets the per-probe threshold
  notes: 'v1 stub — runner not yet implemented. Verify phase fills this in.',
};

// Per-probe TODO stubs. Each probe runner will:
// 1. Start a Claude Code session against workspaceBefore with the probe prompt.
// 2. Capture the tool-call log from the session transcript or hook output.
// 3. Extract the observable metric from the log.
// 4. Repeat for workspaceAfter.
// 5. Compute delta and assess pass/fail against the threshold.

switch (probe) {
  case 'lsp-callers':
    // TODO: implement
    // Prompt: "Find all callers of the `_toMs` helper in the fixture repo."
    // Metric: count of Grep tool calls before the agent reports the complete callers list.
    // Pass: after.metric <= before.metric - 2
    result.notes = 'lsp-callers stub — requires running LSP server in after workspace.';
    break;

  case 'codebase-map':
    // TODO: implement
    // Prompt: "Find all callers of the `_toMs` helper in the fixture repo."
    // Metric: count of Read + Grep + LS calls before the agent reaches the correct answer.
    // Pass: after.metric <= before.metric - 2
    result.notes = 'codebase-map stub — before has no CODEBASE.md; after has one pre-populated with the fixture tree.';
    break;

  case 'scoped-test':
    // TODO: implement
    // Prompt: "Run the tests for the date-utils module."
    // Metric: count of monorepo-wide test invocations (e.g., `npm test` at workspace root).
    // Pass: after.metric === 0 (no monorepo-wide runs)
    result.notes = 'scoped-test stub — after workspace has per-repo CLAUDE.md with scoped test command.';
    break;

  case 'session-reflect':
    // TODO: implement
    // Prompt: scripted session that will produce "actually" in the ## Progress output.
    // Metric: session-reflect.json candidates.length after session ends.
    // Pass: after.metric >= 1 (before.metric === 0 by definition — no reflection step)
    result.notes = 'session-reflect stub — after workspace has BP-10 reflection step in session-end.mjs.';
    break;
}

// Write result file.
const outPath = resolve(output);
const outDir = dirname(outPath);
if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });
writeFileSync(outPath, JSON.stringify(result, null, 2) + '\n', 'utf8');

process.stdout.write(`Result written to: ${outPath}\n`);
